// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import { defineConfig } from "prisma/config";

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    // The Supabase database existed before Prisma migration history was tracked.
    // Keep the original migrations untouched and use a clean, baselined history.
    path: "prisma/migrations_baselined",
  },
  datasource: {
    url: process.env["DATABASE_URL"],
  },
});
